services:
  - type: web
    name: jarvis-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_api:app --host 0.0.0.0 --port $PORT
    autoDeploy: true